# Generated by Django 3.1.4 on 2020-12-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя продукта')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('diagonal', models.CharField(max_length=100, verbose_name='Диагональ')),
                ('display', models.CharField(max_length=100, verbose_name='ТИп дисплея')),
                ('resolution', models.CharField(max_length=100, verbose_name='Разрешение экрана')),
                ('accum_volume', models.CharField(max_length=100, verbose_name='Объем аккамулятора')),
                ('rpm', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=100, verbose_name='Макс.объем встраиваемой памяти')),
                ('frontal_camera', models.CharField(max_length=100, verbose_name='ФРонтальная камера')),
                ('main_camera', models.CharField(max_length=100, verbose_name='Основная камера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='КАтегория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя продукта')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('diagonal', models.CharField(max_length=100, verbose_name='Диагональ')),
                ('display', models.CharField(max_length=100, verbose_name='ТИп дисплея')),
                ('processor_freq', models.CharField(max_length=100, verbose_name='Частота процессора')),
                ('rpm', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('video', models.CharField(max_length=100, verbose_name='ВИдеокарта')),
                ('time_without_charge', models.CharField(max_length=100, verbose_name='Время работы от аккамулятора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='КАтегория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
